///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Context_Main_page
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Context_Main_pageRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c29c9c74-fd3a-4e94-a604-78c1db6ae45e")]
    public partial class Context_Main_pageRepository : RepoGenBaseFolder
    {
        static Context_Main_pageRepository instance = new Context_Main_pageRepository();
        Context_Main_pageRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Context_Main_pageRepositoryFolders.ContextStudioAppFolder _contextstudio;

        /// <summary>
        /// Gets the singleton class instance representing the Context_Main_pageRepository element repository.
        /// </summary>
        [RepositoryFolder("c29c9c74-fd3a-4e94-a604-78c1db6ae45e")]
        public static Context_Main_pageRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Context_Main_pageRepository() 
            : base("Context_Main_pageRepository", "/", null, 0, false, "c29c9c74-fd3a-4e94-a604-78c1db6ae45e", ".\\RepositoryImages\\Context_Main_pageRepositoryc29c9c74.rximgres")
        {
            _applicationundertest = new Context_Main_pageRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _contextstudio = new Context_Main_pageRepositoryFolders.ContextStudioAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c29c9c74-fd3a-4e94-a604-78c1db6ae45e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("82ad5b81-3981-4771-a11c-1b914693485f")]
        public virtual Context_Main_pageRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ContextStudio folder.
        /// </summary>
        [RepositoryFolder("fe9ab298-8f85-4cbd-bca7-b5950d8478a1")]
        public virtual Context_Main_pageRepositoryFolders.ContextStudioAppFolder ContextStudio
        {
            get { return _contextstudio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Context_Main_pageRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("82ad5b81-3981-4771-a11c-1b914693485f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "82ad5b81-3981-4771-a11c-1b914693485f", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("82ad5b81-3981-4771-a11c-1b914693485f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("82ad5b81-3981-4771-a11c-1b914693485f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ContextStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("fe9ab298-8f85-4cbd-bca7-b5950d8478a1")]
        public partial class ContextStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _login_buttonInfo;
            RepoItemInfo _contextsInfo;
            RepoItemInfo _useremailInfo;
            RepoItemInfo _userid_filter_tabInfo;
            RepoItemInfo _filter_buttonInfo;
            RepoItemInfo _clearfiltersInfo;
            RepoItemInfo _contextclassification_filtter_tabInfo;
            RepoItemInfo _qcontextstatidsInfo;
            RepoItemInfo _qdetailedcontextstatidsInfo;
            RepoItemInfo _qcontextcriteriaidsInfo;
            RepoItemInfo _qcontextpagelistidsInfo;

            /// <summary>
            /// Creates a new ContextStudio  folder.
            /// </summary>
            public ContextStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContextStudio", "/dom[@domain='obsidian-staging.conde.io']", parentFolder, 30000, null, false, "fe9ab298-8f85-4cbd-bca7-b5950d8478a1", "")
            {
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "6b6ef4de-3843-40a3-9f8f-add10894e5aa");
                _login_buttonInfo = new RepoItemInfo(this, "Login_button", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "22a5378b-20cc-4f37-bc89-35d40a0f741b");
                _contextsInfo = new RepoItemInfo(this, "Contexts", ".//li[#'contexts']/a[@innertext='Contexts']", 30000, null, "8844f5bb-47fe-4657-88a5-71bc2ce59cf9");
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "052edeec-0aaa-412b-b274-16e9801e67f7");
                _userid_filter_tabInfo = new RepoItemInfo(this, "UserId_filter_tab", ".//select[#'q_user_id']", 30000, null, "96515ea9-5381-4811-b0af-7b6d6ed402e5");
                _filter_buttonInfo = new RepoItemInfo(this, "Filter_button", ".//form[#'new_q']/?/?/input[@name='commit']", 30000, null, "e32ec731-d526-4bb8-9863-f38a3037ef00");
                _clearfiltersInfo = new RepoItemInfo(this, "ClearFilters", ".//form[#'new_q']/?/?/a[@innertext='Clear Filters']", 30000, null, "bc14af30-4168-434d-9dde-b7ab59bf0b5b");
                _contextclassification_filtter_tabInfo = new RepoItemInfo(this, "ContextClassification_filtter_tab", ".//select[#'q_context_classification_id']", 30000, null, "8b162683-6a44-4b92-994a-6e99a91865d4");
                _qcontextstatidsInfo = new RepoItemInfo(this, "QContextStatIds", ".//select[#'q_context_stat_ids']", 30000, null, "0895879a-5e1d-4b35-a462-28ce2fb58f36");
                _qdetailedcontextstatidsInfo = new RepoItemInfo(this, "QDetailedContextStatIds", ".//select[#'q_detailed_context_stat_ids']", 30000, null, "25517e45-f072-474a-aae5-668d4d5ee9fa");
                _qcontextcriteriaidsInfo = new RepoItemInfo(this, "QContextCriteriaIds", ".//select[#'q_context_criteria_ids']", 30000, null, "d824d5b4-0bc5-4e9d-aebf-c7774a324d23");
                _qcontextpagelistidsInfo = new RepoItemInfo(this, "QContextPageListIds", ".//select[#'q_context_page_list_ids']", 30000, null, "8ee61f7e-6948-4e8e-956f-602d0a0c97e9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fe9ab298-8f85-4cbd-bca7-b5950d8478a1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fe9ab298-8f85-4cbd-bca7-b5950d8478a1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("6b6ef4de-3843-40a3-9f8f-add10894e5aa")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("6b6ef4de-3843-40a3-9f8f-add10894e5aa")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The Login_button item.
            /// </summary>
            [RepositoryItem("22a5378b-20cc-4f37-bc89-35d40a0f741b")]
            public virtual Ranorex.InputTag Login_button
            {
                get
                {
                    return _login_buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login_button item info.
            /// </summary>
            [RepositoryItemInfo("22a5378b-20cc-4f37-bc89-35d40a0f741b")]
            public virtual RepoItemInfo Login_buttonInfo
            {
                get
                {
                    return _login_buttonInfo;
                }
            }

            /// <summary>
            /// The Contexts item.
            /// </summary>
            [RepositoryItem("8844f5bb-47fe-4657-88a5-71bc2ce59cf9")]
            public virtual Ranorex.ATag Contexts
            {
                get
                {
                    return _contextsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Contexts item info.
            /// </summary>
            [RepositoryItemInfo("8844f5bb-47fe-4657-88a5-71bc2ce59cf9")]
            public virtual RepoItemInfo ContextsInfo
            {
                get
                {
                    return _contextsInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("052edeec-0aaa-412b-b274-16e9801e67f7")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("052edeec-0aaa-412b-b274-16e9801e67f7")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The UserId_filter_tab item.
            /// </summary>
            [RepositoryItem("96515ea9-5381-4811-b0af-7b6d6ed402e5")]
            public virtual Ranorex.SelectTag UserId_filter_tab
            {
                get
                {
                    return _userid_filter_tabInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The UserId_filter_tab item info.
            /// </summary>
            [RepositoryItemInfo("96515ea9-5381-4811-b0af-7b6d6ed402e5")]
            public virtual RepoItemInfo UserId_filter_tabInfo
            {
                get
                {
                    return _userid_filter_tabInfo;
                }
            }

            /// <summary>
            /// The Filter_button item.
            /// </summary>
            [RepositoryItem("e32ec731-d526-4bb8-9863-f38a3037ef00")]
            public virtual Ranorex.InputTag Filter_button
            {
                get
                {
                    return _filter_buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Filter_button item info.
            /// </summary>
            [RepositoryItemInfo("e32ec731-d526-4bb8-9863-f38a3037ef00")]
            public virtual RepoItemInfo Filter_buttonInfo
            {
                get
                {
                    return _filter_buttonInfo;
                }
            }

            /// <summary>
            /// The ClearFilters item.
            /// </summary>
            [RepositoryItem("bc14af30-4168-434d-9dde-b7ab59bf0b5b")]
            public virtual Ranorex.ATag ClearFilters
            {
                get
                {
                    return _clearfiltersInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ClearFilters item info.
            /// </summary>
            [RepositoryItemInfo("bc14af30-4168-434d-9dde-b7ab59bf0b5b")]
            public virtual RepoItemInfo ClearFiltersInfo
            {
                get
                {
                    return _clearfiltersInfo;
                }
            }

            /// <summary>
            /// The ContextClassification_filtter_tab item.
            /// </summary>
            [RepositoryItem("8b162683-6a44-4b92-994a-6e99a91865d4")]
            public virtual Ranorex.SelectTag ContextClassification_filtter_tab
            {
                get
                {
                    return _contextclassification_filtter_tabInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ContextClassification_filtter_tab item info.
            /// </summary>
            [RepositoryItemInfo("8b162683-6a44-4b92-994a-6e99a91865d4")]
            public virtual RepoItemInfo ContextClassification_filtter_tabInfo
            {
                get
                {
                    return _contextclassification_filtter_tabInfo;
                }
            }

            /// <summary>
            /// The QContextStatIds item.
            /// </summary>
            [RepositoryItem("0895879a-5e1d-4b35-a462-28ce2fb58f36")]
            public virtual Ranorex.SelectTag QContextStatIds
            {
                get
                {
                    return _qcontextstatidsInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The QContextStatIds item info.
            /// </summary>
            [RepositoryItemInfo("0895879a-5e1d-4b35-a462-28ce2fb58f36")]
            public virtual RepoItemInfo QContextStatIdsInfo
            {
                get
                {
                    return _qcontextstatidsInfo;
                }
            }

            /// <summary>
            /// The QDetailedContextStatIds item.
            /// </summary>
            [RepositoryItem("25517e45-f072-474a-aae5-668d4d5ee9fa")]
            public virtual Ranorex.SelectTag QDetailedContextStatIds
            {
                get
                {
                    return _qdetailedcontextstatidsInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The QDetailedContextStatIds item info.
            /// </summary>
            [RepositoryItemInfo("25517e45-f072-474a-aae5-668d4d5ee9fa")]
            public virtual RepoItemInfo QDetailedContextStatIdsInfo
            {
                get
                {
                    return _qdetailedcontextstatidsInfo;
                }
            }

            /// <summary>
            /// The QContextCriteriaIds item.
            /// </summary>
            [RepositoryItem("d824d5b4-0bc5-4e9d-aebf-c7774a324d23")]
            public virtual Ranorex.SelectTag QContextCriteriaIds
            {
                get
                {
                    return _qcontextcriteriaidsInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The QContextCriteriaIds item info.
            /// </summary>
            [RepositoryItemInfo("d824d5b4-0bc5-4e9d-aebf-c7774a324d23")]
            public virtual RepoItemInfo QContextCriteriaIdsInfo
            {
                get
                {
                    return _qcontextcriteriaidsInfo;
                }
            }

            /// <summary>
            /// The QContextPageListIds item.
            /// </summary>
            [RepositoryItem("8ee61f7e-6948-4e8e-956f-602d0a0c97e9")]
            public virtual Ranorex.SelectTag QContextPageListIds
            {
                get
                {
                    return _qcontextpagelistidsInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The QContextPageListIds item info.
            /// </summary>
            [RepositoryItemInfo("8ee61f7e-6948-4e8e-956f-602d0a0c97e9")]
            public virtual RepoItemInfo QContextPageListIdsInfo
            {
                get
                {
                    return _qcontextpagelistidsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
