///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Context_Main_page
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Context_2 recording.
    /// </summary>
    [TestModule("ea28ac83-9feb-4e3e-ba63-49c2d9588d54", ModuleType.Recording, 1)]
    public partial class Context_2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Context_Main_pageRepository repository.
        /// </summary>
        public static Context_Main_pageRepository repo = Context_Main_pageRepository.Instance;

        static Context_2 instance = new Context_2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Context_2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Context_2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 484;776.", repo.ContextStudio.SelfInfo, new RecordItemIndex(0));
            repo.ContextStudio.Self.MoveTo("484;776");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1060;791.", repo.ContextStudio.SelfInfo, new RecordItemIndex(1));
            repo.ContextStudio.Self.MoveTo("1060;791");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '188' on item 'ContextStudio.QContextCriteriaIds'.", repo.ContextStudio.QContextCriteriaIdsInfo, new RecordItemIndex(2));
            repo.ContextStudio.QContextCriteriaIds.Element.SetAttributeValue("TagValue", "188");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1427;269.", repo.ContextStudio.SelfInfo, new RecordItemIndex(3));
            repo.ContextStudio.Self.MoveTo("1427;269");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;696.", repo.ContextStudio.SelfInfo, new RecordItemIndex(4));
            repo.ContextStudio.Self.MoveTo("1439;696");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Filter_button' at 27;9.", repo.ContextStudio.Filter_buttonInfo, new RecordItemIndex(5));
            repo.ContextStudio.Filter_button.Click("27;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 800;773.", repo.ContextStudio.SelfInfo, new RecordItemIndex(6));
            repo.ContextStudio.Self.MoveTo("800;773");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1436;243.", repo.ContextStudio.SelfInfo, new RecordItemIndex(7));
            repo.ContextStudio.Self.MoveTo("1436;243");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;651.", repo.ContextStudio.SelfInfo, new RecordItemIndex(8));
            repo.ContextStudio.Self.MoveTo("1439;651");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 73;11.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(9));
            repo.ContextStudio.ClearFilters.Click("73;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 739;775.", repo.ContextStudio.SelfInfo, new RecordItemIndex(10));
            repo.ContextStudio.Self.MoveTo("739;775");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'ContextStudio.QContextPageListIds'.", repo.ContextStudio.QContextPageListIdsInfo, new RecordItemIndex(11));
            repo.ContextStudio.QContextPageListIds.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1431;241.", repo.ContextStudio.SelfInfo, new RecordItemIndex(12));
            repo.ContextStudio.Self.MoveTo("1431;241");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;541.", repo.ContextStudio.SelfInfo, new RecordItemIndex(13));
            repo.ContextStudio.Self.MoveTo("1439;541");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Filter_button' at 40;15.", repo.ContextStudio.Filter_buttonInfo, new RecordItemIndex(14));
            repo.ContextStudio.Filter_button.Click("40;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 769;773.", repo.ContextStudio.SelfInfo, new RecordItemIndex(15));
            repo.ContextStudio.Self.MoveTo("769;773");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1174;804.", repo.ContextStudio.SelfInfo, new RecordItemIndex(16));
            repo.ContextStudio.Self.MoveTo("1174;804");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1432;352.", repo.ContextStudio.SelfInfo, new RecordItemIndex(17));
            repo.ContextStudio.Self.MoveTo("1432;352");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;667.", repo.ContextStudio.SelfInfo, new RecordItemIndex(18));
            repo.ContextStudio.Self.MoveTo("1439;667");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 65;11.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(19));
            repo.ContextStudio.ClearFilters.Click("65;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
