///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Context_Main_page
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Context recording.
    /// </summary>
    [TestModule("0d297236-68c5-458d-83fa-7b3068ad504d", ModuleType.Recording, 1)]
    public partial class Context : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Context_Main_pageRepository repository.
        /// </summary>
        public static Context_Main_pageRepository repo = Context_Main_pageRepository.Instance;

        static Context instance = new Context();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Context()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Context Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.UserEmail' at 32;13.", repo.ContextStudio.UserEmailInfo, new RecordItemIndex(0));
            repo.ContextStudio.UserEmail.Click("32;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'obs-admin@condenast.com' with focus on 'ContextStudio'.", repo.ContextStudio.SelfInfo, new RecordItemIndex(1));
            repo.ContextStudio.Self.EnsureVisible();
            Keyboard.Press("obs-admin@condenast.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.UserPassword' at 80;29.", repo.ContextStudio.UserPasswordInfo, new RecordItemIndex(2));
            repo.ContextStudio.UserPassword.Click("80;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password' with focus on 'ContextStudio.UserPassword'.", repo.ContextStudio.UserPasswordInfo, new RecordItemIndex(3));
            repo.ContextStudio.UserPassword.PressKeys("password");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Login_button' at 189;26.", repo.ContextStudio.Login_buttonInfo, new RecordItemIndex(4));
            repo.ContextStudio.Login_button.Click("189;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Contexts' at 27;14.", repo.ContextStudio.ContextsInfo, new RecordItemIndex(5));
            repo.ContextStudio.Contexts.Click("27;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 657;781.", repo.ContextStudio.SelfInfo, new RecordItemIndex(6));
            repo.ContextStudio.Self.MoveTo("657;781");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 973;790.", repo.ContextStudio.SelfInfo, new RecordItemIndex(7));
            repo.ContextStudio.Self.MoveTo("973;790");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'ContextStudio.UserId_filter_tab'.", repo.ContextStudio.UserId_filter_tabInfo, new RecordItemIndex(8));
            repo.ContextStudio.UserId_filter_tab.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1428;224.", repo.ContextStudio.SelfInfo, new RecordItemIndex(9));
            repo.ContextStudio.Self.MoveTo("1428;224");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;621.", repo.ContextStudio.SelfInfo, new RecordItemIndex(10));
            repo.ContextStudio.Self.MoveTo("1439;621");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Filter_button' at 28;12.", repo.ContextStudio.Filter_buttonInfo, new RecordItemIndex(11));
            repo.ContextStudio.Filter_button.Click("28;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 579;773.", repo.ContextStudio.SelfInfo, new RecordItemIndex(12));
            repo.ContextStudio.Self.MoveTo("579;773");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 925;779.", repo.ContextStudio.SelfInfo, new RecordItemIndex(13));
            repo.ContextStudio.Self.MoveTo("925;779");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1434;218.", repo.ContextStudio.SelfInfo, new RecordItemIndex(14));
            repo.ContextStudio.Self.MoveTo("1434;218");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;551.", repo.ContextStudio.SelfInfo, new RecordItemIndex(15));
            repo.ContextStudio.Self.MoveTo("1439;551");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 61;8.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(16));
            repo.ContextStudio.ClearFilters.Click("61;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 61;8.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(17));
            repo.ContextStudio.ClearFilters.Click("61;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 581;782.", repo.ContextStudio.SelfInfo, new RecordItemIndex(18));
            repo.ContextStudio.Self.MoveTo("581;782");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1024;802.", repo.ContextStudio.SelfInfo, new RecordItemIndex(19));
            repo.ContextStudio.Self.MoveTo("1024;802");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'ContextStudio.ContextClassification_filtter_tab'.", repo.ContextStudio.ContextClassification_filtter_tabInfo, new RecordItemIndex(20));
            repo.ContextStudio.ContextClassification_filtter_tab.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1428;283.", repo.ContextStudio.SelfInfo, new RecordItemIndex(21));
            repo.ContextStudio.Self.MoveTo("1428;283");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;566.", repo.ContextStudio.SelfInfo, new RecordItemIndex(22));
            repo.ContextStudio.Self.MoveTo("1439;566");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Filter_button' at 37;18.", repo.ContextStudio.Filter_buttonInfo, new RecordItemIndex(23));
            repo.ContextStudio.Filter_button.Click("37;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1429;357.", repo.ContextStudio.SelfInfo, new RecordItemIndex(24));
            repo.ContextStudio.Self.MoveTo("1429;357");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio.ClearFilters' at 77;17.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(25));
            repo.ContextStudio.ClearFilters.MoveTo("77;17");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 70;10.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(26));
            repo.ContextStudio.ClearFilters.Click("70;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 812;774.", repo.ContextStudio.SelfInfo, new RecordItemIndex(27));
            repo.ContextStudio.Self.MoveTo("812;774");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '79' on item 'ContextStudio.QContextStatIds'.", repo.ContextStudio.QContextStatIdsInfo, new RecordItemIndex(28));
            repo.ContextStudio.QContextStatIds.Element.SetAttributeValue("TagValue", "79");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1435;283.", repo.ContextStudio.SelfInfo, new RecordItemIndex(29));
            repo.ContextStudio.Self.MoveTo("1435;283");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;650.", repo.ContextStudio.SelfInfo, new RecordItemIndex(30));
            repo.ContextStudio.Self.MoveTo("1439;650");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio.Filter_button' at 34;8.", repo.ContextStudio.Filter_buttonInfo, new RecordItemIndex(31));
            repo.ContextStudio.Filter_button.MoveTo("34;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Filter_button' at 37;9.", repo.ContextStudio.Filter_buttonInfo, new RecordItemIndex(32));
            repo.ContextStudio.Filter_button.Click("37;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 723;775.", repo.ContextStudio.SelfInfo, new RecordItemIndex(33));
            repo.ContextStudio.Self.MoveTo("723;775");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1143;808.", repo.ContextStudio.SelfInfo, new RecordItemIndex(34));
            repo.ContextStudio.Self.MoveTo("1143;808");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1432;370.", repo.ContextStudio.SelfInfo, new RecordItemIndex(35));
            repo.ContextStudio.Self.MoveTo("1432;370");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1439;592.", repo.ContextStudio.SelfInfo, new RecordItemIndex(36));
            repo.ContextStudio.Self.MoveTo("1439;592");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 77;8.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(37));
            repo.ContextStudio.ClearFilters.Click("77;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 77;8.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(38));
            repo.ContextStudio.ClearFilters.Click("77;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 768;777.", repo.ContextStudio.SelfInfo, new RecordItemIndex(39));
            repo.ContextStudio.Self.MoveTo("768;777");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '2' on item 'ContextStudio.QDetailedContextStatIds'.", repo.ContextStudio.QDetailedContextStatIdsInfo, new RecordItemIndex(40));
            repo.ContextStudio.QDetailedContextStatIds.Element.SetAttributeValue("TagValue", "2");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1425;307.", repo.ContextStudio.SelfInfo, new RecordItemIndex(41));
            repo.ContextStudio.Self.MoveTo("1425;307");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ContextStudio' at 1426;651.", repo.ContextStudio.SelfInfo, new RecordItemIndex(42));
            repo.ContextStudio.Self.MoveTo("1426;651");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.Filter_button' at 37;16.", repo.ContextStudio.Filter_buttonInfo, new RecordItemIndex(43));
            repo.ContextStudio.Filter_button.Click("37;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 683;776.", repo.ContextStudio.SelfInfo, new RecordItemIndex(44));
            repo.ContextStudio.Self.MoveTo("683;776");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ContextStudio' at 1436;350.", repo.ContextStudio.SelfInfo, new RecordItemIndex(45));
            repo.ContextStudio.Self.MoveTo("1436;350");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 49;14.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(46));
            repo.ContextStudio.ClearFilters.Click("49;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextStudio.ClearFilters' at 49;14.", repo.ContextStudio.ClearFiltersInfo, new RecordItemIndex(47));
            repo.ContextStudio.ClearFilters.Click("49;14");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
